# Generated by Django 4.1.7 on 2023-03-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='msg',
            field=models.CharField(max_length=500, null=True, verbose_name='comment'),
        ),
    ]
