# Generated by Django 4.1.7 on 2023-03-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_posts_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='msg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='comment'),
        ),
    ]
