# Generated by Django 4.1.7 on 2023-03-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_posts_msg_posts_body_alter_posts_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
